theme: jekyll-theme-minimal
title: Joseph Oddy
logo: /Monogram_pic.tiff
description: PhD Student at Rothamsted Research trying to understand genetic and environmental regulation of asparagine in wheat grain.
