project:
  type: website

website:
  title: "Joseph Oddy"
  navbar:
    left:
      - href: index.qmd
        text: About
      - analysis.qmd
  sidebar:
    - id: id-links
      title: "Links"
      style: "docked"
      background: light
      logo: /assets/images/MARVIN pic.JPG
      contents:
          - text: "Web of Science"
            href: "https://www.webofscience.com/wos/author/record/HGC-8340-2022"
          - text: "ORCID"
            href: "https://orcid.org/0000-0001-6792-1152"
          - text: "Google Scholar"
            href: "https://scholar.google.com/citations?user=C5t6-asAAAAJ&hl=en"
          - text: "Linkedin"
            href: "https://www.linkedin.com/in/joseph-oddy-879561131/"
          - text: "Piano music"
            href: "https://github.com/JosephOddy/PianoCompositions"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

